//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goliaz.Dto
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class DAYS_REPORT
    {
        public DAYS_REPORT()
        {
            this.REPORT_DAY = new HashSet<REPORT_DAY>();
        }
    
        public int idRegister { get; set; }
        public int idUser { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int day { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual ICollection<REPORT_DAY> REPORT_DAY { get; set; }
    }
}
