//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goliaz.Dto
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DAYS
    {
        public DAYS()
        {
            this.DAYS_CONFIG = new HashSet<DAYS_CONFIG>();
        }
    
        public int idDay { get; set; }
        public Nullable<int> Day { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> completeDay { get; set; }
    
        public virtual ICollection<DAYS_CONFIG> DAYS_CONFIG { get; set; }
    }
}
