//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goliaz.Dto
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class DAYS_CONFIG
    {
        public int idReportNum { get; set; }
        public string name { get; set; }
        public string dataType { get; set; }
        public Nullable<int> idDay { get; set; }
        public Nullable<int> max_reps { get; set; }
        public string description { get; set; }
    
        public virtual DAYS DAYS { get; set; }
    }
}
