//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goliaz.Dto
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class LOG_ERROR
    {
        public int id_log { get; set; }
        public string error { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
