//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goliaz.Dto
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class USERS
    {
        public USERS()
        {
            this.DAYS_REPORT = new HashSet<DAYS_REPORT>();
        }
        public int age { get; set; }
        public int idUser { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public System.DateTime birthDate { get; set; }
        public string gender { get; set; }
        public string nationality { get; set; }
        public string pass { get; set; }
        public string poseidon_pb { get; set; }
        public string hades_pb { get; set; }
        public string venus_pb { get; set; }
        public string estado { get; set; }
        public string codeConfirm { get; set; }
        public Nullable<System.DateTime> REGISTER_DAY { get; set; }
    
        public virtual ICollection<DAYS_REPORT> DAYS_REPORT { get; set; }
    }
}
